export const GET_PRACTICE = "GET_PRACTICE";

export const GET_STUDENT_LIST="GET_STUDENT_LIST";

export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";

export const ADD_SUCCESS_MESSAGE = "ADD_SUCCESS_MESSAGE";
export const REMOVE_SUCCESS_MESSAGE = "REMOVE_SUCCESS_MESSAGE";

export const SET_STUDENT = "SET_STUDENT";
export const SET_CURRENT_INTERNSHIP = "SET_CURRENT_INTERNSHIP";

export const SET_PRACTICE = "SET_PRACTICE";
export const GET_FACULTY_PROFILE = "GET_FACULTY_PROFILE";
